---

  - name: Ensure project root is accessible in project_root.stdout
    command: git rev-parse --show-toplevel
    register: project_root

  - name: "Ensure {{ project_root.stdout }}/ansible/tmp does not exist"
    file:
      path: "{{ project_root.stdout }}/ansible/tmp"
      state: absent