---

  - name: Ensure project root is accessible in project_root.stdout
    command: git rev-parse --show-toplevel
    register: project_root

  - name: "Ensure {{ cloud_functions_archive_name }} does not exist"
    file:
      path: "{{ project_root.stdout }}/ansible/tmp/{{ cloud_functions_archive_name }}"
      state: absent